/* tslint:disable */
/* eslint-disable */
/**
 * Zapper API
 * The Zapper API provides some of the most robust Defi related data, everything from liquidity and prices on different AMMs to complex Defi protocol balances all in one convenient place. In addition, the API also supports bridging between different networks as well as formatted Zap transaction endpoints. <br/><br/><br/> *Enter in our public API key in the Authorize section below to test the endpoints directly in swagger: **96e0cc51-a62e-42ca-acee-910ea7d2a241**
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GasPricesResponse
 */
export interface GasPricesResponse {
    /**
     * Standard gas price in Gwei
     * @type {number}
     * @memberof GasPricesResponse
     */
    standard: number;
    /**
     * Fast gas price in Gwei
     * @type {number}
     * @memberof GasPricesResponse
     */
    fast: number;
    /**
     * Instant gas price in Gwei
     * @type {number}
     * @memberof GasPricesResponse
     */
    instant: number;
}

export function GasPricesResponseFromJSON(json: any): GasPricesResponse {
    return GasPricesResponseFromJSONTyped(json, false);
}

export function GasPricesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GasPricesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'standard': json['standard'],
        'fast': json['fast'],
        'instant': json['instant'],
    };
}

export function GasPricesResponseToJSON(value?: GasPricesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'standard': value.standard,
        'fast': value.fast,
        'instant': value.instant,
    };
}


