[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "https://blockhead-beta.netlify.app"
  to = "https://blockhead.info"
  status = 301
  force = true

[functions]
  external_node_modules = [
    "ethers",
    "etherspot",
    "@ethersproject/bytes",
    "sharp"
  ]
