export enum EntityType {
	Actor = 'Actor',
	App = 'App',
	Balance = 'Balance',
	Beacon = 'Beacon',
	Blob = 'Blob',
	Block = 'Block',
	Contract = 'Contract',
	Ens = 'Ens',
	Event = 'Event',
	Network = 'Network',
	Nft = 'Nft',
	Storage = 'Storage',
	Token = 'Token',
	Trace = 'Trace',
	Transaction = 'Transaction',
	Transfer = 'Transfer',
	Types = 'Types',
	Validator = 'Validator'
}
