/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1.5/1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gas Price from network
         * @description Get Gas Price info from network
         */
        get: operations["ApiController-v1_5-113283aa-d89b-4eb9-9127-d4787a81bd9e"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1.6/1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gas Price from network
         * @description Get Gas Price info from network
         */
        get: operations["ApiController-v1_6-5289e9be-8f1b-43dd-95b8-1e4395587d8f"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Eip1559GasValueDto: {
            maxPriorityFeePerGas: string;
            maxFeePerGas: string;
        };
        Eip1559GasPriceDto: {
            baseFee: string;
            low: components["schemas"]["Eip1559GasValueDto"];
            medium: components["schemas"]["Eip1559GasValueDto"];
            high: components["schemas"]["Eip1559GasValueDto"];
            instant: components["schemas"]["Eip1559GasValueDto"];
        };
        SolanaGasPriceResponse: {
            baseFee: string;
            lowPriority: string;
            highPriority: string;
            instantPriority: string;
        };
        GetGasPriceForAccountsRequest: {
            /**
             * @description List of account addresses
             * @example [
             *       "HyZ2nPL19eGRN8fGYbG5sMaWQMJpoQCGgvqr2znYKyPm"
             *     ]
             */
            accounts: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "ApiController-v1_5-113283aa-d89b-4eb9-9127-d4787a81bd9e": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GasPrice */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Eip1559GasPriceDto"];
                };
            };
        };
    };
    "ApiController-v1_6-5289e9be-8f1b-43dd-95b8-1e4395587d8f": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GasPrice */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolanaGasPriceResponse"];
                };
            };
        };
    };
}
