/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1.5/56": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gas Price from network
         * @description Get Gas Price info from network
         */
        get: operations["ApiController-v1_5-790eb1b8-3b9a-4d9d-89e0-09c233d86122"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1.6/56": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gas Price from network
         * @description Get Gas Price info from network
         */
        get: operations["ApiController-v1_6-1e5c5fc3-2262-4e29-b175-259e26cee723"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LegacyGasPriceResponse: {
            standard: string;
            fast: string;
            instant: string;
        };
        SolanaGasPriceResponse: {
            baseFee: string;
            lowPriority: string;
            highPriority: string;
            instantPriority: string;
        };
        GetGasPriceForAccountsRequest: {
            /**
             * @description List of account addresses
             * @example [
             *       "HyZ2nPL19eGRN8fGYbG5sMaWQMJpoQCGgvqr2znYKyPm"
             *     ]
             */
            accounts: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "ApiController-v1_5-790eb1b8-3b9a-4d9d-89e0-09c233d86122": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GasPrice */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyGasPriceResponse"];
                };
            };
        };
    };
    "ApiController-v1_6-1e5c5fc3-2262-4e29-b175-259e26cee723": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GasPrice */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolanaGasPriceResponse"];
                };
            };
        };
    };
}
