/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface definitions {
  /**
   * Approve CallData response
   */
  ApproveCallData: {
    /**
     * Address of the token to approve
     */
    to: string;
    /**
     * ETH value in wei (for approve is 0)
     */
    value: string;
    /**
     * Network fast gas price
     */
    gasPrice: string;
    /**
     * CallData to sign
     */
    data: string;
  };
  /**
   * Spender address
   */
  SpenderAddress: {
    /**
     * We need to approve your token to this address
     */
    address: string;
  };
  /**
   * Supported Protocols
   */
  Protocols: {
    /**
     * Supported protocols to pass to protocols
     */
    protocols: string[];
  };
  /**
   * Supported tokens (you can also use not supported)
   */
  Tokens: {
    /**
     * Supported tokens
     */
    tokens: definitions["Token"];
  };
  /**
   * Token
   */
  Token: {
    symbol: string;
    name: string;
    address: string;
    decimals: number;
    logoURI: string;
  };
  /**
   * Quote Response
   */
  Quote: {
    /**
     * From token info
     */
    fromToken: definitions["Token"];
    /**
     * To token info
     */
    toToken: definitions["Token"];
    /**
     * To token amount
     */
    toTokenAmount: string;
    /**
     * From token amount
     */
    fromTokenAmount: string;
    /**
     * From token amount
     */
    protocols: definitions["SelectedProtocol"][];
    /**
     * Estimated Gas
     */
    estimatedGas: number;
  };
  /**
   * Swap Response
   */
  Swap: {
    /**
     * From token info
     */
    fromToken: definitions["Token"];
    /**
     * To token info
     */
    toToken: definitions["Token"];
    /**
     * To token amount
     */
    toTokenAmount: string;
    /**
     * From token amount
     */
    fromTokenAmount: string;
    /**
     * From token amount
     */
    protocols: definitions["SelectedProtocol"][];
    /**
     * Ethereum transaction
     */
    tx: definitions["Tx"];
  };
  /**
   * Ethereum transaction
   */
  Tx: {
    from: string;
    to: string;
    data: string;
    value: string;
    gasPrice: string;
    gas: number;
  };
  /**
   * Selected Protocol Info
   */
  SelectedProtocol: {
    name: string;
    part: number;
    fromTokenAddress: string;
    toTokenAddress: string;
  };
}
