/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/portfolio/v4/overview/protocols/current_value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Protocols current value
         * @description Returns the current value for all supported protocols. Data is grouped by chains and addresses.
         */
        get: operations["get_current_value_portfolio_v4_overview_protocols_current_value_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/v4/overview/protocols/profit_and_loss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Protocols profit and loss
         * @description Returns the PnL (Profit and Loss) and ROI (Return on Investment), aggregated across all supported protocols. Data is organized by chains.
         */
        get: operations["get_profit_and_loss_portfolio_v4_overview_protocols_profit_and_loss_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/v4/overview/protocols/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Protocols details
         * @description Provides general information for each protocol's statistics (underlying tokens, current_value, etc.) and protocol-specific metrics (ROI, APR, unclaimed_fees, claimed_fees, etc.). It may include closed positions.
         */
        get: operations["get_details_portfolio_v4_overview_protocols_details_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/v4/overview/erc20/current_value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tokens current value
         * @description Returns the current value for supported tokens. Data is grouped by chains and addresses.
         */
        get: operations["get_current_value_portfolio_v4_overview_erc20_current_value_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/v4/overview/erc20/profit_and_loss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tokens profit and loss
         * @description Returns the PnL (Profit and Loss) and ROI (Return on Investment), aggregated across all supported tokens. Data is organized by chains.
         */
        get: operations["get_profit_and_loss_portfolio_v4_overview_erc20_profit_and_loss_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/v4/overview/erc20/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tokens details
         * @description Provides general information for each token's statistics, including ROI (Return on Investment) and PnL (Profit and Loss). It may include closed positions.
         */
        get: operations["get_details_portfolio_v4_overview_erc20_details_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/v4/general/is_available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Is available
         * @description Check if the service is available.
         */
        get: operations["get_is_available_portfolio_v4_general_is_available_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/v4/general/supported_chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Supported chains
         * @description Returns list of supported chains.
         */
        get: operations["get_supported_chains_portfolio_v4_general_supported_chains_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/v4/general/current_value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * General current value
         * @description Returns the current value for all supported protocols and tokens. Data is grouped by chains and addresses.
         */
        get: operations["get_current_value_portfolio_v4_general_current_value_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/v4/general/profit_and_loss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * General profit and loss
         * @description Returns the PnL (Profit and Loss) and ROI (Return on Investment), aggregated across all supported protocols and tokens. Data is organized by chains.
         */
        get: operations["get_profit_and_loss_portfolio_v4_general_profit_and_loss_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/v4/general/value_chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * General value chart
         * @description Returns value chart for all supported protocols and tokens.
         */
        get: operations["get_value_chart_portfolio_v4_general_value_chart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * TimeRange
         * @enum {string}
         */
        TimeRange: "1day" | "1week" | "1month" | "1year" | "3years";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_current_value_portfolio_v4_overview_protocols_current_value_get: {
        parameters: {
            query: {
                /** @description Addresses */
                addresses: string[];
                /** @description Chain id or nothing */
                chain_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profit_and_loss_portfolio_v4_overview_protocols_profit_and_loss_get: {
        parameters: {
            query: {
                /** @description Addresses */
                addresses: string[];
                /** @description Chain id or nothing */
                chain_id?: number;
                /** @description Timerange */
                timerange?: components["schemas"]["TimeRange"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_details_portfolio_v4_overview_protocols_details_get: {
        parameters: {
            query: {
                /** @description Addresses */
                addresses: string[];
                /** @description Chain id or nothing */
                chain_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_value_portfolio_v4_overview_erc20_current_value_get: {
        parameters: {
            query: {
                /** @description Addresses */
                addresses: string[];
                /** @description Chain id or nothing */
                chain_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profit_and_loss_portfolio_v4_overview_erc20_profit_and_loss_get: {
        parameters: {
            query: {
                /** @description Addresses */
                addresses: string[];
                /** @description Chain id or nothing */
                chain_id?: number;
                /** @description Timerange */
                timerange?: components["schemas"]["TimeRange"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_details_portfolio_v4_overview_erc20_details_get: {
        parameters: {
            query: {
                /** @description Addresses */
                addresses: string[];
                /** @description Chain id or nothing */
                chain_id?: number;
                /** @description Timerange */
                timerange?: components["schemas"]["TimeRange"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_is_available_portfolio_v4_general_is_available_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_supported_chains_portfolio_v4_general_supported_chains_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_current_value_portfolio_v4_general_current_value_get: {
        parameters: {
            query: {
                /** @description Addresses */
                addresses: string[];
                /** @description Chain id or nothing */
                chain_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profit_and_loss_portfolio_v4_general_profit_and_loss_get: {
        parameters: {
            query: {
                /** @description Addresses */
                addresses: string[];
                /** @description Chain id or nothing */
                chain_id?: number;
                /** @description Timerange */
                timerange?: components["schemas"]["TimeRange"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_value_chart_portfolio_v4_general_value_chart_get: {
        parameters: {
            query: {
                /** @description Addresses */
                addresses: string[];
                /** @description Chain id or nothing */
                chain_id?: number;
                /** @description Timerange */
                timerange?: components["schemas"]["TimeRange"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
