/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1.5/1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGasPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Eip1559GasValueResponse: {
            maxPriorityFeePerGas: string;
            maxFeePerGas: string;
        };
        Eip1559GasPriceResponse: {
            baseFee: string;
            low: components["schemas"]["Eip1559GasValueResponse"];
            medium: components["schemas"]["Eip1559GasValueResponse"];
            high: components["schemas"]["Eip1559GasValueResponse"];
            instant: components["schemas"]["Eip1559GasValueResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGasPrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GasPrice */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Eip1559GasPriceResponse"];
                };
            };
        };
    };
}
