// export { default as BananaWalletIcon } from './wallets/BananaWallet.png'
export { default as BraveIcon } from './wallets/Brave.svg'
export { default as Coin98Icon } from './wallets/Coin98.svg'
export { default as CoinbaseWalletIcon } from './wallets/CoinbaseWallet.svg'
export { default as EnkryptIcon } from './wallets/Enkrypt.svg'
export { default as FrameIcon } from './wallets/Frame.svg'
export { default as ImTokenIcon } from './wallets/imToken.svg'
export { default as IntmaxIcon } from './wallets/Intmax.png'
// export { default as LedgerLiveIcon } from './wallets/LedgerLive.svg'
export { default as MetaMaskIcon } from './wallets/MetaMask.svg'
export { default as MyEtherWalletIcon } from './wallets/MyEtherWallet.svg'
export { default as PhantomIcon } from './wallets/Phantom.svg'
// export { default as PortisIcon } from './wallets/Portis.svg'
export { default as RabbyIcon } from './wallets/Rabby.svg'
export { default as RainbowIcon } from './wallets/Rainbow.svg'
export { default as RainbowPngIcon } from './wallets/Rainbow.png'
export { default as RivetIcon } from './wallets/Rivet.svg'
export { default as TahoIcon } from './wallets/Taho.svg'
// export { default as TokenPocketIcon } from './wallets/TokenPocket.svg'
// export { default as TorusIcon } from './wallets/Torus.svg'
export { default as TrustWalletIcon } from './wallets/TrustWallet.svg'
export { default as UniswapExtensionIcon } from './wallets/UniswapExtension.svg'
export { default as WalletConnectIcon } from './wallets/WalletConnect.svg'
export { default as WalletConnect2Icon } from './wallets/WalletConnect2.svg'
