export { default as CoinbaseWalletIcon } from './wallets/CoinbaseWallet.svg'
export { default as MetaMaskIcon } from './wallets/MetaMask.svg'
// export { default as MyEtherWalletIcon } from './wallets/MyEtherWallet.svg'
// export { default as PortisIcon } from './wallets/Portis.svg'
// export { default as LedgerLiveIcon } from './wallets/LedgerLive.svg'
export { default as RainbowIcon } from './wallets/Rainbow.svg'
// export { default as TallyIcon } from './wallets/Tally.svg'
// export { default as TokenPocketIcon } from './wallets/TokenPocket.svg'
// export { default as TorusIcon } from './wallets/Torus.svg'
// export { default as TrustWalletIcon } from './wallets/TrustWallet.svg'
export { default as WalletConnectIcon } from './wallets/WalletConnect.svg'
