// Types/constants
import type { Ethereum } from '$/data/networks/types'
import { NetworkProviderConnectionType, NetworkProviderNodeType } from '$/data/networkProviders/types'
import { networksBySlug } from '$/data/networks'

// https://github.com/blockscout/frontend-configs/tree/main/configs/featured-networks
export const blockscoutProviderConfigs: {
	label: string,
	domain: string,
	networkSlug: Ethereum.NetworkSlug,
	connectionType: NetworkProviderConnectionType,
	nodeType: NetworkProviderNodeType,
	group?: string,
}[] = [
	{
		label: 'Arbitrum Blueberry',
		domain: 'arb-blueberry.gelatoscout.com',
		networkSlug: 'arbitrum-blueberry',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'ARTIS-Σ1',
		domain: 'blockscout.com/artis/sigma1',
		networkSlug: 'artis-sigma1',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Other',
	},
	{
		label: 'Astar (EVM)',
		domain: 'astar.blockscout.com', // blockscout.com/astar
		networkSlug: 'astar-evm',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Astar (Subscan)',
		domain: 'astar.subscan.io',
		networkSlug: 'astar-subscan',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Astar zkEVM',
		domain: 'astar-zkevm.blockscout.com',
		networkSlug: 'astar-zkevm',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Astar zKyoto',
		domain: 'astar-zkyoto.blockscout.com',
		networkSlug: 'astar-zkyoto',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Base Chain',
		domain: 'base.blockscout.com',
		networkSlug: 'base-chain',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Base Göerli',
		domain: 'base-goerli.blockscout.com',
		networkSlug: 'base-goerli',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Base Sepolia',
		domain: 'base-sepolia.blockscout.com',
		networkSlug: 'base-sepolia',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Blackfort',
		domain: 'blackfort.blockscout.com',
		networkSlug: 'blackfort',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Blackfort Testnet',
		domain: 'blackfort-testnet.blockscout.com',
		networkSlug: 'blackfort-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Blast',
		domain: 'blast.blockscout.com',
		networkSlug: 'blast',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Blast Testnet',
		domain: 'blast-testnet.blockscout.com',
		networkSlug: 'blast-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Blockscout Athens-3 Explorer',
		domain: 'zetachain-athens-3.blockscout.com',
		networkSlug: 'zetachain-athens-3',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'CDK Stavanger',
		domain: 'polygon-cdk-stavanger.blockscout.com',
		networkSlug: 'polygon-cdk-stavanger',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Creditcoin Devnet',
		domain: 'creditcoin-devnet.blockscout.com',
		networkSlug: 'creditcoin-devnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Creditcoin Testnet',
		domain: 'creditcoin-testnet.blockscout.com',
		networkSlug: 'creditcoin-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'ETC Mordor',
		domain: 'etc-mordor.blockscout.com',
		networkSlug: 'etc-mordor',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Ethereum',
		domain: 'eth.blockscout.com',
		networkSlug: 'ethereum',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Ethereum Classic',
		domain: 'etc.blockscout.com', // blockscout.com/etc/mainnet
		networkSlug: 'ethereum-classic',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Etherlink',
		domain: 'explorer.etherlink.com',
		networkSlug: 'etherlink',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Etherlink Testnet',
		domain: 'testnet-explorer.etherlink.com',
		networkSlug: 'etherlink-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Fuse',
		domain: 'explorer.fuse.io',
		networkSlug: 'fuse',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Garnet Testnet',
		domain: 'explorer.garnetchain.com',
		networkSlug: 'garnet-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Gnosis Chain',
		domain: 'gnosis.blockscout.com',
		networkSlug: 'gnosis',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Gnosis Chain Chiado',
		domain: 'gnosis-chiado.blockscout.com',
		networkSlug: 'gnosis-chiado',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Goerli',
		domain: 'eth-goerli.blockscout.com',
		networkSlug: 'ethereum-goerli',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Holesky',
		domain: 'eth-holesky.blockscout.com',
		networkSlug: 'ethereum-holesky',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Immutable',
		domain: 'explorer.immutable.com',
		networkSlug: 'immutable',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Immutable Testnet',
		domain: 'explorer.testnet.immutable.com',
		networkSlug: 'immutable-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'IOTA EVM Mainnet',
		domain: 'explorer.evm.iota.org',
		networkSlug: 'iota-evm-mainnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'IOTA EVM Testnet',
		domain: 'explorer.evm.testnet.iotaledger.net',
		networkSlug: 'iota-evm-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'IOTA L1 Mainnet',
		domain: 'explorer.iota.org',
		networkSlug: 'iota-l1-mainnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'IOTA L1 testnet',
		domain: 'explorer.iota.org/iota-testnet',
		networkSlug: 'iota-l1-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Kusama',
		domain: 'kusama.subscan.io',
		networkSlug: 'kusama',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Other',
	},
	{
		label: 'LightLink Pegasus',
		domain: 'pegasus.lightlink.blockscout.com',
		networkSlug: 'lightlink-pegasus',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'LightLink Phoenix',
		domain: 'phoenix.lightlink.blockscout.com',
		networkSlug: 'lightlink-phoenix',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Lisk Mainnet',
		domain: 'blockscout.lisk.com',
		networkSlug: 'lisk-mainnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Lisk Sepolia Testnet',
		domain: 'sepolia-blockscout.lisk.com',
		networkSlug: 'lisk-sepolia',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'LUKSO L14',
		domain: 'blockscout.com/lukso/l14',
		networkSlug: 'lukso-l14',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Other',
	},
	{
		label: 'Neon',
		domain: 'neon.blockscout.com',
		networkSlug: 'neon',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Neon Devnet',
		domain: 'neon-devnet.blockscout.com',
		networkSlug: 'neon-devnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Neon Mainnet',
		domain: 'neon.blockscout.com',
		networkSlug: 'neon-mainnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Official testnet explorer',
		domain: 'explorer.zetachain.com',
		networkSlug: 'zetachain-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Omni Testnet',
		domain: 'omni-testnet.blockscout.com',
		networkSlug: 'omni-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Omni X-Explorer',
		domain: 'explorer.testnet.omni.network',
		networkSlug: 'omni-x-explorer',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'OP Celestia Raspberry',
		domain: 'opcelestia-raspberry.gelatoscout.com',
		networkSlug: 'op-celestia-raspberry',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Optimism',
		domain: 'optimism.blockscout.com',
		networkSlug: 'optimism',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Optimism Bedrock Beta',
		domain: 'blockscout.com/optimism/bedrock-beta',
		networkSlug: 'optimism-bedrock-beta',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Optimism Goerli',
		domain: 'optimism-goerli.blockscout.com',
		networkSlug: 'optimism-goerli',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Optimism Opcraft',
		domain: 'blockscout.com/optimism/opcraft',
		networkSlug: 'optimism-opcraft',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Other',
	},
	{
		label: 'Optimism Sepolia',
		domain: 'optimism-sepolia.blockscout.com',
		networkSlug: 'optimism-sepolia',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Pegasus Testnet',
		domain: 'pegasus.lightlink.io',
		networkSlug: 'pegasus-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Phoenix Mainnet',
		domain: 'phoenix.lightlink.io',
		networkSlug: 'phoenix',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Playblock',
		domain: 'explorer.playblock.io',
		networkSlug: 'playblock',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Playnance',
		domain: 'playnance.blockscout.com',
		networkSlug: 'playnance',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'POA',
		domain: 'blockscout.com/poa/core',
		networkSlug: 'poa',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Other',
	},
	{
		label: 'POA Sokol',
		domain: 'blockscout.com/poa/sokol',
		networkSlug: 'poa-sokol',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Other',
	},
	{
		label: 'Polkadot',
		domain: 'polkadot.subscan.io',
		networkSlug: 'polkadot',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Other',
	},
	{
		label: 'Polygon',
		domain: 'polygon.blockscout.com',
		networkSlug: 'polygon',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Polygon Blackberry',
		domain: 'polygon-blackberry.gelatoscout.com',
		networkSlug: 'polygon-blackberry',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Puppynet Testnet',
		domain: 'puppyscan.shib.io',
		networkSlug: 'puppynet-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 're.al',
		domain: 'explorer.re.al',
		networkSlug: 'real',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Redstone',
		domain: 'explorer.redstone.xyz',
		networkSlug: 'redstone',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Reya Cronos',
		domain: 'reya-cronos.blockscout.com',
		networkSlug: 'reya-cronos',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Reya Mainnet',
		domain: 'explorer.reya.network',
		networkSlug: 'reya-mainnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Rootstock Mainnet',
		domain: 'rootstock.blockscout.com',
		networkSlug: 'rootstock-mainnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Rootstock Testnet',
		domain: 'rootstock-testnet.blockscout.com',
		networkSlug: 'rootstock-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'RSK',
		domain: 'blockscout.com/rsk/mainnet',
		networkSlug: 'rsk',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Sepolia',
		domain: 'eth-sepolia.blockscout.com',
		networkSlug: 'ethereum-sepolia',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Shibarium',
		domain: 'shibariumscan.io',
		networkSlug: 'shibarium',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Shibuya (EVM)',
		domain: 'shibuya.blockscout.com', // blockscout.com/shibuya
		networkSlug: 'shibuya-evm',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Shibuya (Subscan)',
		domain: 'shibuya.subscan.io',
		networkSlug: 'shibuya-subscan',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Shiden (EVM)',
		domain: 'shiden.blockscout.com', // blockscout.com/shiden
		networkSlug: 'shiden-evm',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Shiden (Subscan)',
		domain: 'shiden.subscan.io',
		networkSlug: 'shiden-subscan',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Shimmer EVM',
		domain: 'explorer.evm.shimmer.network', // iota-shimmer.blockscout.com
		networkSlug: 'shimmer-evm',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Shimmer EVM Testnet',
		domain: 'explorer.evm.testnet.shimmer.network',
		networkSlug: 'shimmer-evm-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Shimmer L1 Mainnet',
		domain: 'explorer.shimmer.network/shimmer',
		networkSlug: 'shimmer-l1-mainnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Shimmer L1 Testnet',
		domain: 'explorer.shimmer.network/testnet',
		networkSlug: 'shimmer-l1-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Spark',
		domain: 'explorer.fusespark.io',
		networkSlug: 'spark',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'Stability',
		domain: 'stability.blockscout.com',
		networkSlug: 'stability',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Stability Testnet',
		domain: 'stability-testnet.blockscout.com',
		networkSlug: 'stability-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Unreal',
		domain: 'unreal.blockscout.com',
		networkSlug: 'unreal',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'ZetaChain Mainnet',
		domain: 'zetachain.blockscout.com',
		networkSlug: 'zetachain-mainnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'ZetaChain testnet',
		domain: 'zetachain-athens-3.blockscout.com',
		networkSlug: 'zetachain-testnet',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
	{
		label: 'zkEVM',
		domain: 'zkevm.blockscout.com',
		networkSlug: 'zkevm',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'zkSync',
		domain: 'zksync.blockscout.com',
		networkSlug: 'zksync',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'zkSync Sepolia',
		domain: 'zksync-sepolia.blockscout.com',
		networkSlug: 'zksync-sepolia',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Zora',
		domain: 'explorer.zora.energy',
		networkSlug: 'zora',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Mainnets',
	},
	{
		label: 'Zora Sepolia',
		domain: 'sepolia.explorer.zora.energy',
		networkSlug: 'zora-sepolia',
		connectionType: NetworkProviderConnectionType.RPC,
		nodeType: NetworkProviderNodeType.Default,
		group: 'Testnets',
	},
]

export const blockscoutInstancesByChainId = Object.fromEntries(
	blockscoutProviderConfigs
		.filter(config => (
			config.networkSlug in networksBySlug
		))
		.map(config => [
			networksBySlug[config.networkSlug].chainId,
			config,
		])
)

export const getBlockscoutRestEndpoint = (
	chainId: Ethereum.ChainID,
) => (
	`https://${blockscoutInstancesByChainId[chainId].domain}/api/v2`
)
