// Types/constants
import type { Ethereum } from '$/data/networks/types'

// https://github.com/blockscout/frontend-configs/tree/main/configs/featured-networks
export const blockscoutProviderConfigs: {
	label: string,
	chainId?: Ethereum.ChainID,
	explorerUrl: string,
	group?: string,
}[] = [
	
	{
		label: 'Arbitrum Blueberry',
		chainId: 88153591557,
		explorerUrl: 'arb-blueberry.gelatoscout.com',
		group: 'Mainnets',
	},
	{
		label: 'ARTIS-Σ1',
		chainId: undefined,
		explorerUrl: 'blockscout.com/artis/sigma1',
		group: 'Other',
	},
	{
		label: 'Astar (EVM)',
		chainId: 592,
		explorerUrl: 'astar.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Astar (Subscan)',
		chainId: undefined,
		explorerUrl: 'astar.subscan.io',
		group: 'Mainnets',
	},
	{
		label: 'Astar zkEVM',
		chainId: undefined,
		explorerUrl: 'astar-zkevm.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Astar zKyoto',
		chainId: undefined,
		explorerUrl: 'astar-zkyoto.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Base Chain',
		chainId: 8453,
		explorerUrl: 'base.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Base Göerli',
		chainId: 84531,
		explorerUrl: 'base-goerli.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'Base Sepolia',
		chainId: 84532,
		explorerUrl: 'base-sepolia.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'Blackfort',
		chainId: 4999,
		explorerUrl: 'blackfort.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Blackfort Testnet',
		chainId: 4777,
		explorerUrl: 'blackfort-testnet.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Blast',
		chainId: 81457,
		explorerUrl: 'blast.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Blast Testnet',
		chainId: 168587773,
		explorerUrl: 'blast-testnet.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Blockscout Athens-3 Explorer',
		chainId: 7001,
		explorerUrl: 'zetachain-athens-3.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'CDK Stavanger',
		chainId: 686669576,
		explorerUrl: 'polygon-cdk-stavanger.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Creditcoin Devnet',
		chainId: 102032,
		explorerUrl: 'creditcoin-devnet.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'Creditcoin Testnet',
		chainId: 102031,
		explorerUrl: 'creditcoin-testnet.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'ETC Mordor',
		chainId: 63,
		explorerUrl: 'etc-mordor.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'Ethereum',
		chainId: 1,
		explorerUrl: 'eth.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Ethereum Classic',
		chainId: 61,
		explorerUrl: 'etc.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Etherlink',
		chainId: 42793,
		explorerUrl: 'explorer.etherlink.com',
		group: 'Mainnets',
	},
	{
		label: 'Etherlink Testnet',
		chainId: 128123,
		explorerUrl: 'testnet-explorer.etherlink.com',
		group: 'Mainnets',
	},
	{
		label: 'Fuse',
		chainId: 122,
		explorerUrl: 'explorer.fuse.io',
		group: 'Mainnets',
	},
	{
		label: 'Garnet Testnet',
		chainId: 17069,
		explorerUrl: 'explorer.garnetchain.com',
		group: 'Testnets',
	},
	{
		label: 'Gnosis Chain',
		chainId: 100,
		explorerUrl: 'gnosis.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Gnosis Chain Chiado',
		chainId: 10200,
		explorerUrl: 'gnosis-chiado.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'Goerli',
		chainId: 5,
		explorerUrl: 'eth-goerli.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'Holesky',
		chainId: 17000,
		explorerUrl: 'eth-holesky.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'Immutable',
		chainId: 13371,
		explorerUrl: 'explorer.immutable.com',
		group: 'Mainnets',
	},
	{
		label: 'Immutable Testnet',
		chainId: 13473,
		explorerUrl: 'explorer.testnet.immutable.com',
		group: 'Testnets',
	},
	{
		label: 'IOTA EVM Mainnet',
		chainId: 8822,
		explorerUrl: 'explorer.evm.iota.org',
		group: 'Mainnets',
	},
	{
		label: 'IOTA EVM Testnet',
		chainId: 1075,
		explorerUrl: 'explorer.evm.testnet.iotaledger.net',
		group: 'Testnets',
	},
	{
		label: 'IOTA L1 Mainnet',
		chainId: undefined,
		explorerUrl: 'explorer.iota.org',
		group: 'Mainnets',
	},
	{
		label: 'IOTA L1 testnet',
		chainId: undefined,
		explorerUrl: 'explorer.iota.org/iota-testnet',
		group: 'Testnets',
	},
	{
		label: 'Kusama',
		chainId: undefined,
		explorerUrl: 'kusama.subscan.io',
		group: 'Other',
	},
	{
		label: 'LightLink Pegasus',
		chainId: undefined,
		explorerUrl: 'pegasus.lightlink.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'LightLink Phoenix',
		chainId: undefined,
		explorerUrl: 'phoenix.lightlink.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Lisk Mainnet',
		chainId: 1135,
		explorerUrl: 'blockscout.lisk.com',
		group: 'Mainnets',
	},
	{
		label: 'Lisk Sepolia Testnet',
		chainId: 4202,
		explorerUrl: 'sepolia-blockscout.lisk.com',
		group: 'Mainnets',
	},
	{
		label: 'LUKSO L14',
		chainId: undefined,
		explorerUrl: 'blockscout.com/lukso/l14',
		group: 'Other',
	},
	{
		label: 'Neon',
		chainId: 245022934,
		explorerUrl: 'neon.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Neon Devnet',
		chainId: 245022926,
		explorerUrl: 'neon-devnet.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'Neon Mainnet',
		chainId: 245022934,
		explorerUrl: 'neon.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Official testnet explorer',
		chainId: undefined,
		explorerUrl: 'explorer.zetachain.com',
		group: 'Testnets',
	},
	{
		label: 'Omni Testnet',
		chainId: 165,
		explorerUrl: 'omni-testnet.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'Omni X-Explorer',
		chainId: undefined,
		explorerUrl: 'explorer.testnet.omni.network',
		group: 'Testnets',
	},
	{
		label: 'OP Celestia Raspberry',
		chainId: 123420111,
		explorerUrl: 'opcelestia-raspberry.gelatoscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Optimism',
		chainId: 10,
		explorerUrl: 'optimism.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Optimism Bedrock Beta',
		chainId: undefined,
		explorerUrl: 'blockscout.com/optimism/bedrock-beta',
		group: 'Testnets',
	},
	{
		label: 'Optimism Goerli',
		chainId: 420,
		explorerUrl: 'optimism-goerli.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'Optimism Opcraft',
		chainId: undefined,
		explorerUrl: 'blockscout.com/optimism/opcraft',
		group: 'Other',
	},
	{
		label: 'Optimism Sepolia',
		chainId: 11155420,
		explorerUrl: 'optimism-sepolia.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'Pegasus Testnet',
		chainId: 1891,
		explorerUrl: 'pegasus.lightlink.io',
		group: 'Testnets',
	},
	{
		label: 'Phoenix Mainnet',
		chainId: 1890,
		explorerUrl: 'phoenix.lightlink.io',
		group: 'Mainnets',
	},
	{
		label: 'Playblock',
		chainId: 1829,
		explorerUrl: 'explorer.playblock.io',
		group: 'Mainnets',
	},
	{
		label: 'Playnance',
		chainId: undefined,
		explorerUrl: 'playnance.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'POA',
		chainId: undefined,
		explorerUrl: 'blockscout.com/poa/core',
		group: 'Other',
	},
	{
		label: 'POA Sokol',
		chainId: undefined,
		explorerUrl: 'blockscout.com/poa/sokol',
		group: 'Other',
	},
	{
		label: 'Polkadot',
		chainId: undefined,
		explorerUrl: 'polkadot.subscan.io',
		group: 'Other',
	},
	{
		label: 'Polygon',
		chainId: 137,
		explorerUrl: 'polygon.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Polygon Blackberry',
		chainId: 94204209,
		explorerUrl: 'polygon-blackberry.gelatoscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Puppynet Testnet',
		chainId: 157,
		explorerUrl: 'puppyscan.shib.io',
		group: 'Testnets',
	},
	{
		label: 're.al',
		chainId: 111188,
		explorerUrl: 'explorer.re.al',
		group: 'Mainnets',
	},
	{
		label: 'Redstone',
		chainId: 690,
		explorerUrl: 'explorer.redstone.xyz',
		group: 'Mainnets',
	},
	{
		label: 'Reya Cronos',
		chainId: 89346162,
		explorerUrl: 'reya-cronos.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Reya Mainnet',
		chainId: 1729,
		explorerUrl: 'explorer.reya.network',
		group: 'Mainnets',
	},
	{
		label: 'Rootstock Mainnet',
		chainId: 30,
		explorerUrl: 'rootstock.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Rootstock Testnet',
		chainId: 31,
		explorerUrl: 'rootstock-testnet.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'RSK',
		chainId: undefined,
		explorerUrl: 'blockscout.com/rsk/mainnet',
		group: 'Mainnets',
	},
	{
		label: 'Sepolia',
		chainId: 11155111,
		explorerUrl: 'eth-sepolia.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'Shibarium',
		chainId: undefined,
		explorerUrl: 'shibariumscan.io',
		group: 'Mainnets',
	},
	{
		label: 'Shibuya (EVM)',
		chainId: 81,
		explorerUrl: 'shibuya.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'Shibuya (Subscan)',
		chainId: undefined,
		explorerUrl: 'shibuya.subscan.io',
		group: 'Testnets',
	},
	{
		label: 'Shiden (EVM)',
		chainId: 336,
		explorerUrl: 'shiden.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Shiden (Subscan)',
		chainId: undefined,
		explorerUrl: 'shiden.subscan.io',
		group: 'Mainnets',
	},
	{
		label: 'Shimmer EVM',
		chainId: 148,
		explorerUrl: 'explorer.evm.shimmer.network',
		group: 'Mainnets',
	},
	{
		label: 'Shimmer EVM Testnet',
		chainId: 1073,
		explorerUrl: 'explorer.evm.testnet.shimmer.network',
		group: 'Testnets',
	},
	{
		label: 'Shimmer L1 Mainnet',
		chainId: undefined,
		explorerUrl: 'explorer.shimmer.network/shimmer',
		group: 'Mainnets',
	},
	{
		label: 'Shimmer L1 Testnet',
		chainId: undefined,
		explorerUrl: 'explorer.shimmer.network/testnet',
		group: 'Testnets',
	},
	{
		label: 'Spark',
		chainId: 123,
		explorerUrl: 'explorer.fusespark.io',
		group: 'Testnets',
	},
	{
		label: 'Stability',
		chainId: 101010,
		explorerUrl: 'stability.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Stability Testnet',
		chainId: 20180427,
		explorerUrl: 'stability-testnet.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Unreal',
		chainId: 18233,
		explorerUrl: 'unreal.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'ZetaChain Mainnet',
		chainId: undefined,
		explorerUrl: 'zetachain.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'ZetaChain testnet',
		chainId: 7001,
		explorerUrl: 'zetachain-athens-3.blockscout.com',
		group: 'Testnets',
	},
	{
		label: 'zkEVM',
		chainId: 1101,
		explorerUrl: 'zkevm.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'zkSync',
		chainId: 324,
		explorerUrl: 'zksync.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'zkSync Sepolia',
		chainId: 300,
		explorerUrl: 'zksync-sepolia.blockscout.com',
		group: 'Mainnets',
	},
	{
		label: 'Zora',
		chainId: 7777777,
		explorerUrl: 'explorer.zora.energy',
		group: 'Mainnets',
	},
	{
		label: 'Zora Sepolia',
		chainId: 999999999,
		explorerUrl: 'sepolia.explorer.zora.energy',
		group: 'Testnets',
	},
]

export const blockscoutInstancesByChainId = Object.fromEntries(
	blockscoutProviderConfigs
		.map(config => [
			config.chainId,
			config,
		])
)

export const getBlockscoutRestEndpoint = (
	chainId: Ethereum.ChainID,
) => (
	`https://${blockscoutInstancesByChainId[chainId].explorerUrl}/api/v2`
)
