/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1.6/501": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gas Price from network
         * @description Get Gas Price info from network
         */
        get: operations["ApiController-v1_6-86849a0f-6b19-46a4-8c9f-05709bc9909f"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1.6/501/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gas Price from network for solana accounts
         * @description Get Gas Price info from network for solana accounts
         */
        post: operations["ApiController-getGasPriceForAccounts-fcf1d5de-c1df-44f7-b4a3-5ffb4fafe1a8"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LegacyGasPriceResponse: {
            standard: string;
            fast: string;
            instant: string;
        };
        SolanaGasPriceResponse: {
            baseFee: string;
            lowPriority: string;
            highPriority: string;
            instantPriority: string;
        };
        GetGasPriceForAccountsRequest: {
            /**
             * @description List of account addresses
             * @example [
             *       "HyZ2nPL19eGRN8fGYbG5sMaWQMJpoQCGgvqr2znYKyPm"
             *     ]
             */
            accounts: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "ApiController-v1_6-86849a0f-6b19-46a4-8c9f-05709bc9909f": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GasPrice */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolanaGasPriceResponse"];
                };
            };
        };
    };
    "ApiController-getGasPriceForAccounts-fcf1d5de-c1df-44f7-b4a3-5ffb4fafe1a8": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetGasPriceForAccountsRequest"];
            };
        };
        responses: {
            /** @description GasPrice */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolanaGasPriceResponse"];
                };
            };
        };
    };
}
